#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mlChallenger import fetch_stock_history, fetch_universe, month_keys
from momentumV05Backtest import walk_forward_predictions
from momentumV05Features import build_feature_rows
from momentumV051Backtest import run_v051_ablation

START_DATE = "2021-08-11"
ETF_0050_SPLIT_DATE = "2025-06-18"
ETF_0050_SPLIT_RATIO = 4.0


def pct(x):
    return "—" if x is None else f"{x * 100:.2f}%"


def num(x, suffix=""):
    return "—" if x is None else f"{x:.2f}{suffix}"


def adjust_0050(rows):
    out = []
    for row in rows:
        r = dict(row)
        if r["date"] < ETF_0050_SPLIT_DATE:
            for key in ("open", "high", "low", "close"):
                if r.get(key) is not None:
                    r[key] = float(r[key]) / ETF_0050_SPLIT_RATIO
        out.append(r)
    return out


def markdown(report):
    strategies = report["strategies"]
    lines = [
        "# Momentum Rotation Challenger v0.5.1 — Calibration + Trend Ablation",
        "",
        f"Period: **{report['period']['start']} → {report['period']['end']}**",
        "",
        "All model probabilities are generated by the same monthly expanding walk-forward OOS stream used by v0.5. The model layer is unchanged; this experiment changes only decision calibration, trend gating and turnover controls.",
        "",
        "## Pre-registered v0.5.1 candidate",
        "",
        "- Momentum Top-5 entry / Top-10 hysteresis",
        "- soft trend: at least 2 of 4 conditions pass (MA alignment, MA20 slope, volume, MA20 distance)",
        "- ensemble continuation probability in the cross-sectional Top 30%",
        "- minimum 10 trading-day hold before soft exits",
        "- 5 percentage-point rebalance band",
        "- +20% take profit / -20% stop loss remain hard exits",
        "",
        "## Results",
        "",
        "| Mode | Net return | CAGR | Max DD | Sharpe | Turnover | Precision@K | Buys | Excess vs TAIEX | Excess vs 0050 |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for s in strategies:
        m = s["metrics"]
        t = m.get("totalReturn")
        ex_t = None if t is None or m.get("taiexReturn") is None else t - m["taiexReturn"]
        ex_50 = None if t is None or m.get("0050Return") is None else t - m["0050Return"]
        lines.append(
            f"| {s['mode']} | {pct(t)} | {pct(m.get('annualizedReturn'))} | {pct(m.get('maxDrawdown'))} | {num(m.get('sharpe'))} | "
            f"{num(m.get('turnover'), 'x')} | {pct(m.get('precisionAtK'))} | {m.get('buyCount', 0)} | {pct(ex_t)} | {pct(ex_50)} |"
        )
    verdict = report["verdict"]
    lines += [
        "",
        "## Decision gate",
        "",
        f"- v0.5.1 candidate beats Momentum-only after costs: **{verdict['beatsMomentumReturn']}**",
        f"- candidate improves Sharpe: **{verdict['improvesSharpe']}**",
        f"- candidate improves Max DD: **{verdict['improvesDrawdown']}**",
        f"- candidate reduces turnover: **{verdict['reducesTurnover']}**",
        f"- promotion gate passed: **{verdict['promotionPassed']}**",
        "",
        "Diagnostics are not allowed to redefine the candidate after seeing the table. Absolute thresholds and trend variants are included to explain failure modes, not to cherry-pick a new Champion.",
        "",
        "0050 is a split-adjusted price-return benchmark (official 4:1 split effective 2025-06-18); dividends are not reinvested.",
    ]
    return "\n".join(lines) + "\n"


def main():
    months = month_keys(72)
    histories, taiex = fetch_universe(month_count=72, workers=5)
    benchmark_0050 = adjust_0050(fetch_stock_history("0050", months))
    rows = build_feature_rows(histories, taiex, include_unmatured=True)
    end_date = max(r["date"] for r in taiex)
    predicted, training_log = walk_forward_predictions(rows, START_DATE, end_date)
    strategies = run_v051_ablation(predicted, histories, taiex, benchmark_0050, START_DATE, end_date)

    by_mode = {s["mode"]: s for s in strategies}
    mom = by_mode["momentum_only"]["metrics"]
    cand = by_mode["full_v051"]["metrics"]
    beats_return = cand["totalReturn"] > mom["totalReturn"]
    improves_sharpe = (cand.get("sharpe") or -999) > (mom.get("sharpe") or -999)
    improves_dd = cand["maxDrawdown"] > mom["maxDrawdown"]
    reduces_turnover = cand["turnover"] < mom["turnover"]
    verdict = {
        "beatsMomentumReturn": beats_return,
        "improvesSharpe": improves_sharpe,
        "improvesDrawdown": improves_dd,
        "reducesTurnover": reduces_turnover,
        "promotionPassed": all((beats_return, improves_sharpe, improves_dd, reduces_turnover)),
    }

    report = {
        "version": "v0.5.1",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "period": {"start": START_DATE, "end": end_date},
        "design": {
            "candidate": "full_v051",
            "softTrendMin": 2,
            "ensembleEntryPercentile": 0.70,
            "ensembleExitPercentile": 0.40,
            "minimumHoldTradingDays": 10,
            "rebalanceBand": 0.05,
            "entryRank": 5,
            "exitRank": 10,
        },
        "walkForwardTraining": training_log,
        "strategies": strategies,
        "verdict": verdict,
        "benchmark": {
            "0050": "split-adjusted price return; 4:1 split effective 2025-06-18; dividends not reinvested",
        },
    }
    out = ROOT / "data/backtests/momentum_rotation_v0.5.1.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    md = ROOT / "docs/MOMENTUM_ROTATION_V051.md"
    md.parent.mkdir(parents=True, exist_ok=True)
    md.write_text(markdown(report), encoding="utf-8")
    print(markdown(report))


if __name__ == "__main__":
    main()
